name: CI (Build Verification)

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v7

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Cache Processed Images
        uses: actions/cache@v6
        with:
          path: .image-cache
          key: ${{ runner.os }}-image-cache-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-image-cache-

      - name: Build Static Site
        run: npm run build

      - name: run Lighthouse CI
        run: |
          npm install -g @lhci/cli@0.15.x
          lhci autorun
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
