name: PR checks

on:
  pull_request:
    branches: [ develop ]

jobs:
  make-sure-it-builds:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm install
      - run: npm run build
